name: Publish

on:
  push:
    branch: master
    paths: setup.py # only when version changes

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

    - name: checkout helloworld
      uses: actions/checkout@main

    - name: set up Python
      uses: actions/setup-python@v2

    - name: install python packages
      run: pip install setuptools wheel twine

    - name: build
      run: python setup.py sdist bdist_wheel

    - name: publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload  --repository testpypi dist/*

    # - name: PyPA Publish
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/
