name: publish

on:
  push:
    branch: master
    paths: setup.py # only when version changes

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

    - name: checkout helloworld
      uses: actions/checkout@main

    - name: set up Python
      uses: actions/setup-python@v2

    - name: test helloworld
      run: python -B tests.py

    - name: install publishing packages
      run: pip install setuptools build twine

    - name: build
      run: python -m build

    - name: publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload  --repository testpypi dist/*

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #
  #   - name: set up Python
  #     uses: actions/setup-python@v2
  #
  #   - name: install hbar
  #     run: pip install -i https://test.pypi.org/simple/ hbar
  #
  #   - name: run test
  #     run: python -c 'import hbar; assert True'
