name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout helloworld
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install python packages
      run: pip install setuptools wheel twine

    - name: Build
      run: python setup.py sdist bdist_wheel

    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload  --repository testpypi dist/*
