name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checkout helloworld
      uses: actions/checkout@v2

    - name: set up Python
      uses: actions/setup-python@v2

    - name: run test
      run: python tests.py
