name: test hbar

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: checkout helloworld
      uses: actions/checkout@main

    - name: set up Python
      uses: actions/setup-python@v2

    - name: run test
      run: python -B tests.py

    - name: what is github.head_ref?
      run: echo ${{ github.head_ref }}
