name: test hbar

on: push

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

    - name: checkout helloworld
      uses: actions/checkout@main

    - name: set up Python
      uses: actions/setup-python@v2

    - name: run test
      run: python -B tests.py
